{% set name = "macs2" %}
{% set version = "2.2.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://files.pythonhosted.org/packages/72/70/8b55d06b660d1546b359eb67ad84d775cb82de6f50fde2a7c2438fbd9971/MACS2-2.2.4.tar.gz
  sha256: b131aadc8f5fd94bec35308b821e1f7585def788d2e7c756fc8cac402ffee25b

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "

requirements:
  build:
    - "{{ compiler('c') }}"
  host:
    - python <3
    - cython
    - pip
    - numpy >=1.6
    - r-base
  run:
    - numpy >=1.6
    - python <3
    - r-base

test:
  commands:
    - macs2 -h

about:
  home: http://github.com/taoliu/MACS/
  license: BSD
  license_family: BSD
  license_file: LICENSE
  summary: Model Based Analysis for ChIP-Seq data
