{% set version = "1.1" %}

package:
  name: blobtools
  version: {{ version }}

source:
  url: https://github.com/DRL/blobtools/archive/v{{ version }}.tar.gz
  sha256: 6883b3ee1ac383220b38b1be59681e9d724e7f7c5cc1430351903cd54b5bb86e

build:
  noarch: python
  number: 0

requirements:
  host:
    - python <3
    - pip
    - docopt
    - matplotlib
    - ujson
    - samtools
  run:
    - python <3
    - docopt
    - matplotlib
    - ujson
    - samtools
    - curl
    - openssl


test:
  commands:
    - blobtools -h

about:
  home: https://blobtools.readme.io/docs/what-is-blobtools
  license: GPLv3
  summary: 'Modular command-line solution for visualisation, quality control and taxonomic partitioning of genome datasets'
  license_family: GPL

extra:
  identifiers:
    - doi:10.12688/f1000research.12232.1
