{% set version="0.0.5" %}

package:
  name: mango
  version: {{ version }}

source:
  url: https://search.maven.org/remotecontent?filepath=org/bdgenomics/mango/mango-distribution/{{ version }}/mango-distribution-{{ version }}-bin.tar.gz
  md5: f438bdbe93e855db1dae077fa28ff3f7

build:
  number: 0
  noarch: generic

requirements:
  run:
    - python
    - bdgenomics.mango =={{ version }}
    - bdgenomics.mango.pileup =={{ version }}
    - openjdk >=8,<9
    - pyspark

test:
  # Python imports
  imports:
    - bdgenomics.mango
    - bdgenomics.mango.pileup
  commands:
    - mango-submit --help
    - mango-notebook --help
    - make_genome --help
about:
  home: https://github.com/bigdatagenomics/mango
  license: Apache 2
  summary: Scalable genomics visualization tool built on Apache Spark
